#!/bin/bash

int1=0
int2=0

inputs()
{
  printf "Enter two integers: "
  read -a vals
  int1=${vals[0]}
  int2=${vals[1]}
}

exitPrompt()
{
   read -p "Do you wish to continue? [y]es or [n]o: " ans
   if [$ans == 'n']
   then
        echo "Exiting the script. Have a nice day!"
        break
   else
        continue
   fi
}

while (true)

do
clear
printf "Choose from the follwing operations: \n"
printf "[a]Addition [b]Subtraction [c] Multiplication [d]Division\n"
read -p "### Your choice: " choice

case $choice in

[aA])
inputs
res=$((int1+int2))
;;

[bB])
inputs
res=$((int1-int2))
;;

[cC])
inputs
res=$((int1*int2))
;;

[dD])
inputs
if (int2 == 0) then
res=0
echo "Cannot divide by 0"
else
res=$((int1/int2))
;;

*)
res=0
echo "Wrong choice!"

esac

echo "The result is: " $res
exitPrompt
done
